language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.8.7
  - DJANGO_VERSION=1.9
install:
  - pip install -q -r requirements-tests.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
script:
  - py.test --cov=avam tests.py
  - coverage run --source=avam tests.py
after_success: coveralls
