# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('w', 'Washable'), ('c', 'Cartridge'), ('s', 'Scrolling')], max_length=1)),
                ('max_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('replaceable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LampAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hours', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LEDLightAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='asset_types.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='MovingLightAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_types.LampAsset')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_types.ModelType')),
                ('other_accessories', models.ManyToManyField(to='asset_types.GenericAccessory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectorAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamp_count', models.PositiveIntegerField(default=1)),
                ('filter_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_types.FilterAsset')),
                ('lamp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_types.LampAsset')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_types.ModelType')),
                ('other_accessories', models.ManyToManyField(to='asset_types.GenericAccessory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ledlightasset',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_types.ModelType'),
        ),
        migrations.AddField(
            model_name='ledlightasset',
            name='other_accessories',
            field=models.ManyToManyField(to='asset_types.GenericAccessory'),
        ),
        migrations.AddField(
            model_name='lampasset',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_types.ModelType'),
        ),
        migrations.AddField(
            model_name='lampasset',
            name='other_accessories',
            field=models.ManyToManyField(to='asset_types.GenericAccessory'),
        ),
        migrations.AddField(
            model_name='genericasset',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_types.ModelType'),
        ),
        migrations.AddField(
            model_name='genericasset',
            name='other_accessories',
            field=models.ManyToManyField(to='asset_types.GenericAccessory'),
        ),
        migrations.AddField(
            model_name='genericaccessory',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_types.ModelType'),
        ),
        migrations.AddField(
            model_name='genericaccessory',
            name='other_accessories',
            field=models.ManyToManyField(to='asset_types.GenericAccessory'),
        ),
        migrations.AddField(
            model_name='filterasset',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_types.ModelType'),
        ),
        migrations.AddField(
            model_name='filterasset',
            name='other_accessories',
            field=models.ManyToManyField(to='asset_types.GenericAccessory'),
        ),
        migrations.AlterUniqueTogether(
            name='modeltype',
            unique_together=set([('manufacturer', 'name')]),
        ),
    ]
