# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterasset',
            name='other_accessories',
            field=models.ManyToManyField(blank=True, to='asset_types.GenericAccessory'),
        ),
        migrations.AlterField(
            model_name='genericaccessory',
            name='other_accessories',
            field=models.ManyToManyField(blank=True, to='asset_types.GenericAccessory'),
        ),
        migrations.AlterField(
            model_name='genericasset',
            name='other_accessories',
            field=models.ManyToManyField(blank=True, to='asset_types.GenericAccessory'),
        ),
        migrations.AlterField(
            model_name='lampasset',
            name='other_accessories',
            field=models.ManyToManyField(blank=True, to='asset_types.GenericAccessory'),
        ),
        migrations.AlterField(
            model_name='ledlightasset',
            name='other_accessories',
            field=models.ManyToManyField(blank=True, to='asset_types.GenericAccessory'),
        ),
        migrations.AlterField(
            model_name='movinglightasset',
            name='other_accessories',
            field=models.ManyToManyField(blank=True, to='asset_types.GenericAccessory'),
        ),
        migrations.AlterField(
            model_name='projectorasset',
            name='other_accessories',
            field=models.ManyToManyField(blank=True, to='asset_types.GenericAccessory'),
        ),
    ]
