# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTagImageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('header_text', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code_size', models.CharField(blank=True, help_text='Size of the QR Code. (Can be in percent "%") Leave blank for "auto"', max_length=30, null=True)),
                ('code_text_location', models.CharField(choices=[('a', 'Above'), ('b', 'Below'), ('n', 'None')], default='b', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTagPrintTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('dpi', models.FloatField(default=300.0, help_text='Dots per inch')),
                ('columns_per_row', models.IntegerField()),
                ('column_spacing', models.CharField(blank=True, help_text='Space between columns. Can be pixels (px) or inches (in, "). Leave blank for no spacing', max_length=30, null=True)),
                ('rows_per_page', models.IntegerField()),
                ('row_spacing', models.CharField(blank=True, help_text='Space between rows. Can be pixels (px) or inches (in, "). Leave blank for no spacing', max_length=30, null=True)),
                ('asset_tag_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettags.AssetTagImageTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PaperFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('width', models.FloatField(default=8.5, help_text='Page Width (inches)')),
                ('height', models.FloatField(default=11.0, help_text='Page Height (inches')),
                ('top_margin', models.FloatField(default=0.5)),
                ('bottom_margin', models.FloatField(default=0.5)),
                ('left_margin', models.FloatField(default=0.2)),
                ('right_margin', models.FloatField(default=0.2)),
            ],
        ),
        migrations.AddField(
            model_name='assettagprinttemplate',
            name='paper_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettags.PaperFormat'),
        ),
    ]
