# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettags', '0002_auto_20151229_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettagimagetemplate',
            name='header_text_location',
            field=models.CharField(choices=[('a', 'Above'), ('b', 'Below'), ('l', 'Left'), ('r', 'Right'), ('n', 'None')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='assettagimagetemplate',
            name='code_text_location',
            field=models.CharField(choices=[('a', 'Above'), ('b', 'Below'), ('l', 'Left'), ('r', 'Right'), ('n', 'None')], default='b', max_length=1),
        ),
    ]
