# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingLightLampModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('max_hours', models.PositiveIntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettypes.Manufacturer')),
                ('other_accessories', models.ManyToManyField(blank=True, to='assettypes.GenericAccessoryModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='FilterModel',
            new_name='ProjectorFilterModel',
        ),
        migrations.RenameModel(
            old_name='LampModel',
            new_name='ProjectorLampModel',
        ),
        migrations.AlterField(
            model_name='movinglightmodel',
            name='lamp_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettypes.MovingLightLampModel'),
        ),
    ]
