# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettypes', '0002_auto_20151223_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCameraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettypes.Manufacturer')),
                ('other_accessories', models.ManyToManyField(blank=True, to='assettypes.GenericAccessoryModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='videocameramodel',
            unique_together=set([('manufacturer', 'model_name')]),
        ),
    ]
