# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettypes', '0003_auto_20160203_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraLensModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('focal_length_wide', models.DecimalField(decimal_places=2, max_digits=6)),
                ('focal_length_tele', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fstop_wide', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fstop_tele', models.DecimalField(decimal_places=2, max_digits=4)),
                ('zoom_extender_ratio', models.FloatField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettypes.Manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LensMountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectorLensModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('throw_ratio_wide', models.FloatField()),
                ('throw_ratio_tele', models.FloatField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettypes.Manufacturer')),
                ('other_accessories', models.ManyToManyField(blank=True, to='assettypes.GenericAccessoryModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cameralensmodel',
            name='mount_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assettypes.LensMountType'),
        ),
        migrations.AddField(
            model_name='cameralensmodel',
            name='other_accessories',
            field=models.ManyToManyField(blank=True, to='assettypes.GenericAccessoryModel'),
        ),
    ]
