# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettypes', '0005_auto_20160204_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LightingProfileChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='assettypes.LightingProfile')),
            ],
        ),
        migrations.AddField(
            model_name='ledlightmodel',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='assettypes.LightingProfile'),
        ),
        migrations.AddField(
            model_name='movinglightmodel',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='assettypes.LightingProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='lightingprofilechannel',
            unique_together=set([('profile', 'index')]),
        ),
    ]
