# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='linked_categories',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
