# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('assettypes', '0002_auto_20151223_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=True)),
                ('retired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_acquired', models.DateTimeField(auto_now_add=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assettypes.GenericAccessoryModel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=True)),
                ('retired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_acquired', models.DateTimeField(auto_now_add=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assettypes.GenericModel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LEDLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=True)),
                ('retired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_acquired', models.DateTimeField(auto_now_add=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assettypes.LEDLightModel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovingLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=True)),
                ('retired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_acquired', models.DateTimeField(auto_now_add=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assettypes.MovingLightModel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovingLightLamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=True)),
                ('retired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_acquired', models.DateTimeField(auto_now_add=True)),
                ('current_usage', models.DurationField(default=datetime.timedelta(0))),
                ('expected_life', models.DurationField(blank=True, null=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assettypes.MovingLightLampModel')),
                ('installed_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lamps', to='assets.MovingLight')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=True)),
                ('retired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_acquired', models.DateTimeField(auto_now_add=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assettypes.ProjectorModel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectorFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=True)),
                ('retired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_acquired', models.DateTimeField(auto_now_add=True)),
                ('current_usage', models.DurationField(default=datetime.timedelta(0))),
                ('expected_life', models.DurationField(blank=True, null=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assettypes.ProjectorFilterModel')),
                ('installed_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='assets.Projector')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectorLamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=True)),
                ('retired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_acquired', models.DateTimeField(auto_now_add=True)),
                ('current_usage', models.DurationField(default=datetime.timedelta(0))),
                ('expected_life', models.DurationField(blank=True, null=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assettypes.ProjectorLampModel')),
                ('installed_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lamps', to='assets.Projector')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
