# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20151223_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_in_use', models.BooleanField(default=True)),
                ('temp_retired', models.BooleanField(default=False)),
                ('temp_notes', models.TextField(null=True)),
                ('temp_date_acquired', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='genericaccessory',
            name='temp_asset_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='genericasset',
            name='temp_asset_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='ledlight',
            name='temp_asset_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='movinglight',
            name='temp_asset_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='movinglightlamp',
            name='temp_asset_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='projector',
            name='temp_asset_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='projectorfilter',
            name='temp_asset_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='projectorlamp',
            name='temp_asset_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
    ]
