# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 20:19
from __future__ import unicode_literals

from django.db import migrations

def build_assets(apps, schema_editor):
    model_names = [
        'ProjectorLamp',
        'MovingLightLamp',
        'ProjectorFilter',
        'GenericAsset',
        'GenericAccessory',
        'Projector',
        'MovingLight',
        'LEDLight',
    ]
    field_names = [
        'in_use',
        'retired',
        'notes',
        'date_acquired',
    ]
    Asset = apps.get_model('assets', 'Asset')
    for model_name in model_names:
        model = apps.get_model('assets', model_name)
        for obj in model.objects.all():
            asset = Asset.objects.create()
            for field_name in field_names:
                temp_fname = '_'.join(['temp', field_name])
                fval = getattr(obj, field_name)
                setattr(asset, temp_fname, fval)
            asset.save()
            obj.temp_asset_ptr = asset
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20160130_1416'),
    ]

    operations = [
        migrations.RunPython(build_assets)
    ]
