# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20160130_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericaccessory',
            old_name='temp_asset_ptr',
            new_name='asset_ptr',
        ),
        migrations.RenameField(
            model_name='genericasset',
            old_name='temp_asset_ptr',
            new_name='asset_ptr',
        ),
        migrations.RenameField(
            model_name='ledlight',
            old_name='temp_asset_ptr',
            new_name='asset_ptr',
        ),
        migrations.RenameField(
            model_name='movinglight',
            old_name='temp_asset_ptr',
            new_name='asset_ptr',
        ),
        migrations.RenameField(
            model_name='movinglightlamp',
            old_name='temp_asset_ptr',
            new_name='asset_ptr',
        ),
        migrations.RenameField(
            model_name='projector',
            old_name='temp_asset_ptr',
            new_name='asset_ptr',
        ),
        migrations.RenameField(
            model_name='projectorfilter',
            old_name='temp_asset_ptr',
            new_name='asset_ptr',
        ),
        migrations.RenameField(
            model_name='projectorlamp',
            old_name='temp_asset_ptr',
            new_name='asset_ptr',
        ),
    ]
