# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20160130_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericaccessory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genericasset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ledlight',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movinglight',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movinglightlamp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projector',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projectorfilter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projectorlamp',
            name='id',
        ),
        migrations.AlterField(
            model_name='genericaccessory',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='genericasset',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='ledlight',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='movinglight',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='movinglightlamp',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='projector',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='projectorfilter',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='projectorlamp',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset'),
        ),
    ]
