# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20160130_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='temp_in_use',
            new_name='in_use',
        ),
    ]
