# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettypes', '0003_auto_20160203_1203'),
        ('locations', '0001_initial'),
        ('assets', '0010_asset_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCamera',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset')),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assettypes.VideoCameraModel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('assets.asset',),
        ),
    ]
