# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_projectorlens_videocameralens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectorlens',
            options={'verbose_name_plural': 'Projector lenses'},
        ),
        migrations.AlterModelOptions(
            name='videocameralens',
            options={'verbose_name_plural': 'Video camera lenses'},
        ),
    ]
