# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettypes', '0006_auto_20160212_0946'),
        ('assets', '0013_auto_20160212_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledlight',
            name='dmx_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledlight',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assettypes.LightingProfile'),
        ),
        migrations.AddField(
            model_name='movinglight',
            name='dmx_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movinglight',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assettypes.LightingProfile'),
        ),
    ]
