from django.urls import path

from assettags import views

app_name = 'assettags'
urlpatterns = [
    path('lookup/',
        views.asset_tag_lookup,
        name='assettag_lookup',
    ),
    path('lookup/<str:tag_code>/',
        views.asset_tag_lookup,
        name='assettag_lookup_coded',
    ),
    path('assign/',
        views.asset_tag_assign,
        name='asset_tag_assign_form',
    ),
    path('assign/<int:content_type_id>/<int:object_id>/',
        views.asset_tag_assign,
        name='asset_tag_assign',
    ),
    path('assettag_item/<int:tag_code>/',
        views.AssetTagItemView.as_view(),
        name='assettag_item',
    ),
    path('assettag_image/<int:pk>/',
        views.AssetTagImageView.as_view(),
        name='assettag_image',
    ),
    path('assettag_image/file/<int:pk>/',
        views.AssetTagImageView.as_view(),
        {'as_file':True},
        name='assettag_image_file',
    ),
    path('print/',
        views.print_tags,
        name='print_tags',
    ),
]
