# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectupdate',
            options={'ordering': ['-datetime']},
        ),
    ]
